id: P008FFB08
initial_creation_type: ocr
source_metadata:
  volumes:
    0374a41c057b44dca23ec4b27e00657d:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ''
      total_pages: 1872
      volume_number: 114
